import type { IdeaDraft } from '../types.ts'

// Combination shard: things the child combines into new things, so the space of
// results is far larger than the list of parts. Every idea below has parts whose
// behaviour is learned by use, and results that only make sense once it is.

export const ideas: readonly IdeaDraft[] = [
  {
    id: 'combination-01',
    name: 'Pinch Garden',
    loop: 'The child pinches lumps from clay pots and folds them into each other, so the colours streak and then blend the longer they knead, and each tinted bud in a row opens when a lump of its own tint is pressed against it.',
    verb: 'knead',
    ageBand: [3, 6],
    engine: 'combination',
    secondaryEngines: ['expression'],
    lens: 'physical-toy',
    toy: 'clay',
    play5:
      'The child keeps one clean lump aside, adds a pinch at a time to steer a tint on purpose, and stops kneading before three colours dull to brown, so they open the pale and deep buds that only careful blending reaches.',
  },
  {
    id: 'combination-02',
    name: 'Costume Street',
    loop: 'The child drops hats, capes, boots, and props onto a wobbly figure that strolls a small street moving as its outfit says, where some pairs make a movement neither piece has alone and a sleeping dog and a shy bird answer particular outfits.',
    verb: 'dress',
    ageBand: [2, 5],
    engine: 'combination',
    secondaryEngines: ['other-minds'],
    lens: 'physical-toy',
    toy: 'dress-up',
    play5:
      'The child dresses the figure on purpose for the dog or the bird, such as boots with a cape to glide over the fence, because they remember which pairs made which movement and which outfit wakes the dog.',
  },
  {
    id: 'combination-03',
    name: 'Sideways Wheels',
    loop: 'The child snaps wheel, spring, heavy, and plain bricks together in any direction, lets go, and the creation lurches, hops, or rolls across a lumpy table with a gap and a step, then tips off the edge.',
    verb: 'snap',
    ageBand: [5, 8],
    engine: 'combination',
    secondaryEngines: ['emergence'],
    lens: 'physical-toy',
    toy: 'building-bricks',
    play5:
      'The child mounts a wheel on a brick side and a spring under the nose on purpose, because they learned that orientation changes what a brick does, and builds a hopper for the gap that every rolling car fell into.',
  },
  {
    id: 'combination-04',
    name: 'Dip, Shrink, Sift',
    loop: 'The child drops pieces (slope, fork, paint dip, shrinker, sieve, bell) onto a pegboard, and marbles roll through them in order, being painted, shrunk, or filtered, with every fork and sieve sending a marble by what it has become.',
    verb: 'divert',
    ageBand: [6, 9],
    engine: 'combination',
    secondaryEngines: ['emergence'],
    lens: 'physical-toy',
    toy: 'marble-run',
    play5:
      'The child puts the dip before the fork so only red marbles turn left, and the shrinker before the sieve so only small ones drop through, chaining two changes in an order that works one way round and not the other.',
  },
  {
    id: 'combination-05',
    name: 'Window Cradle',
    loop: 'The child drags a stretched string loop over four fingertip pegs and taps a peg to drop its loop, and every crossing the string makes closes a cell that lights up as a coloured window.',
    verb: 'hook',
    ageBand: [7, 10],
    engine: 'combination',
    secondaryEngines: ['mastery'],
    lens: 'physical-toy',
    toy: 'string-figures',
    play5:
      'The child repeats a three-hook sequence they remember to make the same figure on purpose, then drops a single peg to turn it into a different figure they first found by accident.',
  },
  {
    id: 'combination-06',
    name: 'Sway and Settle',
    loop: 'The child hangs shapes from bar ends and bars from other bars, and every bar tips toward its heavier side, swings, and settles, a level one turning slowly on its hook.',
    verb: 'hang',
    ageBand: [4, 7],
    engine: 'combination',
    secondaryEngines: ['mastery'],
    lens: 'other',
    toy: null,
    play5:
      'The child slides a heavy shape close to the middle and a light one far out because they learned a bar balances that way, and hangs a small whole mobile from one end to balance a big shape.',
  },
  {
    id: 'combination-07',
    name: 'Clatter Line',
    loop: 'The child couples engines, log cars, balloon cars, and springy cars in any order, and the train chugs a hilly loop where a strong engine pulls, a balloon car lifts its neighbours, a log car drags, and the weakest hitch snaps.',
    verb: 'couple',
    ageBand: [3, 6],
    engine: 'combination',
    secondaryEngines: ['emergence'],
    lens: 'other',
    toy: null,
    play5:
      'The child parks a balloon car beside the log car and a pusher engine at the back on purpose, because they have watched what the hill does to each, and waits at the slope to see the whole train float over it.',
  },
  {
    id: 'combination-08',
    name: 'Cog Meadow',
    loop: 'The child drops toothed wheels of different sizes onto pegs and turns the first with a finger, wheels that touch turn each other the opposite way, the last one drives a windmill or a waddling duck, and a ring of three wheels jams and shudders.',
    verb: 'mesh',
    ageBand: [5, 8],
    engine: 'combination',
    secondaryEngines: ['mystery'],
    lens: 'other',
    toy: null,
    play5:
      'The child chains a small wheel into a big one for a slow strong turn, adds one wheel to flip the duck the other way, and steers clear of three-wheel rings, because they learned that sizes change the turn and each mesh flips the spin.',
  },
  {
    id: 'combination-09',
    name: 'Jar of Layers',
    loop: 'The child pours syrupy, watery, oily, and fizzy liquids into a tall jar, each settles into its own layer or blends where a finger stirs it, and dropped floaters bob to the layer that suits them.',
    verb: 'pour',
    ageBand: [5, 8],
    engine: 'combination',
    secondaryEngines: ['mystery'],
    lens: 'other',
    toy: null,
    play5:
      'The child pours with a light trickle to keep the layers clean, stirs only two neighbours to make a new in-between layer, and floats the grape where two layers meet, because they learned what sinks, floats, and blends.',
  },
  {
    id: 'combination-10',
    name: 'Loose Strings',
    loop: 'The child ties strings from a puppet\'s hands, feet, and head to slots on a crossbar, rocks the bar with a finger, and each limb lifts when its string pulls tight and dangles when it goes slack.',
    verb: 'rig',
    ageBand: [7, 10],
    engine: 'combination',
    secondaryEngines: ['expression'],
    lens: 'other',
    toy: null,
    play5:
      'The child ties an opposite hand and foot to the same slot to make the puppet walk, then leaves one string slack so a foot lands late, choreographing a step they had only seen by accident.',
  },
  {
    id: 'combination-11',
    name: 'Flare Ring',
    loop: 'The child seats hopping creatures on a ring of twelve beats, each hopping at its own steady rhythm (a small one every second beat, a middling one every third, a tall one every fourth), and a lantern flares whenever several land together.',
    verb: 'stagger',
    ageBand: [8, 11],
    engine: 'combination',
    secondaryEngines: ['emergence'],
    lens: 'other',
    toy: null,
    play5:
      'The child seats a third-beat hopper and a fourth-beat hopper so their flares meet once a round, then fills the gaps with a second-beat hopper, planning a light pattern before placing anyone.',
  },
  {
    id: 'combination-12',
    name: 'Skipped a Generation',
    loop: 'The child pairs two meadow creatures and a hatchling appears, blending their bodies by hidden rules (hues mix, ears follow the longer, spots skip a generation), then keeps it to pair again or lets it wander off.',
    verb: 'cross',
    ageBand: [10, 12],
    engine: 'combination',
    secondaryEngines: ['mystery'],
    lens: 'other',
    toy: null,
    play5:
      'The child pairs two spotless grandchildren of a spotted creature because they know spots skip a generation, raising a spotted, long-eared hatchling on purpose.',
  },
  {
    id: 'combination-13',
    name: 'Wheels Within Wheels',
    loop: 'The child pins spinning arms end to end and drags each arm\'s tip to set how it turns, and a pen at the last tip draws a curve across the paper as the arms whirl.',
    verb: 'whirl',
    ageBand: [10, 12],
    engine: 'combination',
    secondaryEngines: ['expression'],
    lens: 'other',
    toy: null,
    play5:
      'The child sets the outer arm turning the opposite way at three turns to the inner arm\'s one to draw a three-petal flower on purpose, reading the petals off the two turns after meeting it once by accident.',
  },
  {
    id: 'combination-14',
    name: 'Crossed Wires',
    loop: 'The child drags wires from pressure plates that beetles trundle over to lamps, a drawbridge, and small gates (not, both, either, delay), and the courtyard answers each wiring, a not-gate looped back on itself flickering its lamp.',
    verb: 'wire',
    ageBand: [10, 12],
    engine: 'combination',
    secondaryEngines: ['emergence'],
    lens: 'other',
    toy: null,
    play5:
      'The child loops a not-gate through a delay to make a steady blinker on purpose, then wires two blinkers into a both-gate for a beat neither gives alone, constructions that only make sense after learning what each part does.',
  },
]
