import type { IdeaDraft } from '../types.ts'

// Emergence shard: a few simple rules interact so outcomes are not scripted.
// Physical-toy ideas: bubbles (01), ant-farm (04), dominoes (05),
// spinning-top (06), pinball (09).

export const ideas: readonly IdeaDraft[] = [
  {
    id: 'emergence-01',
    name: 'Hover Bubbles',
    loop: 'The child holds a finger at the wand to swell a bubble and lifts to let it go; fresh bubbles float up, cool, and sink, and two that touch merge into one whose float or sink is the blend of the pair.',
    verb: 'blow',
    ageBand: [2, 5],
    engine: 'emergence',
    secondaryEngines: ['mystery'],
    lens: 'physical-toy',
    toy: 'bubbles',
    play5:
      'The child times two blows so a rising bubble meets a sinking one and the merged bubble hangs in mid-air, a trick they hit by accident on play 1 and now aim.',
  },
  {
    id: 'emergence-02',
    name: 'Fledgling Whirl',
    loop: 'The child rests a finger on a meadow with a few stumps and a flock of fledglings drifts in and circles it; a quick swipe scatters them and a slow drag pulls the circling ring along like a ribbon.',
    verb: 'coax',
    ageBand: [2, 5],
    engine: 'emergence',
    secondaryEngines: ['other-minds'],
    lens: 'other',
    toy: null,
    play5:
      'The child expects a still finger to spin the birds into a ring and a slow drag to carry it, and leads the whole ring around a stump in one piece instead of chasing stragglers.',
  },
  {
    id: 'emergence-03',
    name: 'Rising Giants',
    loop: 'The child drags a tray of small and big soft balls back and forth, and the balls shuffle so the big ones climb to the top while the small ones sift underneath.',
    verb: 'jostle',
    ageBand: [3, 6],
    engine: 'emergence',
    secondaryEngines: ['mystery'],
    lens: 'other',
    toy: null,
    play5:
      'The child knows a long steady shake lifts the big balls out of the pile and shakes on purpose to bring one buried giant to the surface, where on play 1 shaking only seemed to mix everything.',
  },
  {
    id: 'emergence-04',
    name: 'Tidy Ants',
    loop: 'The child pours mixed-colour beads onto a sand cross-section, and wandering ants lift lone beads and set them down beside beads of the same colour, so heaps grow with nobody planning them.',
    verb: 'scatter',
    ageBand: [3, 6],
    engine: 'emergence',
    secondaryEngines: ['other-minds'],
    lens: 'physical-toy',
    toy: 'ant-farm',
    play5:
      'The child plants a single bead where a heap should start, knowing the ants will pile that colour around it, and steers each colour into the corner they chose.',
  },
  {
    id: 'emergence-05',
    name: 'Small Tips Big',
    loop: 'The child drags to lay standing tiles along a path in small, middle, or large size and pushes the first; each falling tile topples the next only if the next is not much taller than itself.',
    verb: 'trace',
    ageBand: [5, 8],
    engine: 'emergence',
    secondaryEngines: ['mystery'],
    lens: 'physical-toy',
    toy: 'dominoes',
    play5:
      'The child lays a row whose tiles grow step by step so a nudge on the smallest tile brings down a giant slab, a run that fizzles when built from one size on play 1.',
  },
  {
    id: 'emergence-06',
    name: 'Wobble Bowl',
    loop: 'The child winds a top by circling a finger on it and lets go in a shallow bowl; the top holds near the middle while it spins fast, wobbles out in widening loops as it slows, and clacks into other tops on the way.',
    verb: 'wind',
    ageBand: [5, 8],
    engine: 'emergence',
    secondaryEngines: ['mastery'],
    lens: 'physical-toy',
    toy: 'spinning-top',
    play5:
      'The child reads a top\'s spin before letting go, winding one slow so its widening loops drift into a resting top at the rim and winding another fast to hold the middle, where on play 1 every path was a surprise.',
  },
  {
    id: 'emergence-07',
    name: 'Spot or Stripe',
    loop: 'The child dabs dye on a blank animal shape and the dye spreads and pushes back on itself, settling into spots, stripes, or swirls depending on how the dabs sit.',
    verb: 'dab',
    ageBand: [5, 8],
    engine: 'emergence',
    secondaryEngines: ['expression'],
    lens: 'other',
    toy: null,
    play5:
      'The child dabs lone drops to grow round spots and a close row to grow stripes, and plans a zebra tail and a leopard back on the same animal before any dye moves.',
  },
  {
    id: 'emergence-08',
    name: 'Lantern Vine',
    loop: 'The child holds a finger as a warm lamp and a vine creeps toward it, forking at the tips; branches left in shade shrivel, so the vine is shaped by where the lamp has been.',
    verb: 'shine',
    ageBand: [6, 9],
    engine: 'emergence',
    secondaryEngines: ['expression'],
    lens: 'other',
    toy: null,
    play5:
      'The child leads the vine around a wall by carrying the lamp just ahead of its tips in an arc, knowing it grows toward its brightest branch and drops the shaded ones, where on play 1 it only chased the finger straight into the wall.',
  },
  {
    id: 'emergence-09',
    name: 'Quarter-Turn Table',
    loop: 'The child holds the left or right side to raise a flipper and bat a ball into a ring of bumpers; each hit turns that bumper a quarter-turn, so the table remembers its hits and bounces the ball differently each time.',
    verb: 'flip',
    ageBand: [7, 10],
    engine: 'emergence',
    secondaryEngines: ['mastery'],
    lens: 'physical-toy',
    toy: 'pinball',
    play5:
      'The child reads the bumpers\' turned arrows and bats the ball to bump three of them into a closed loop that keeps it circling, a trap that play 1\'s random bounces never held long enough to notice.',
  },
  {
    id: 'emergence-10',
    name: 'Lockstep Ticks',
    loop: 'The child slides each pendulum\'s weight to set its tempo, then lets go of the loose board they all stand on; the board\'s small shakes pull their swings into step, and holding the board still keeps them apart.',
    verb: 'tune',
    ageBand: [7, 10],
    engine: 'emergence',
    secondaryEngines: ['rule-play'],
    lens: 'other',
    toy: null,
    play5:
      'The child knows a freed board pulls swings into step and a held board keeps them apart, so tunes two groups and frees the board at the moment they choose, making the one-camp or two-camp beat they planned.',
  },
  {
    id: 'emergence-11',
    name: 'Two-Stone Pond',
    loop: 'The child taps or holds the pond to make ripples that spread, cross, and add together, and corks on the water bob wherever crests meet and rest where the ripples cancel.',
    verb: 'pulse',
    ageBand: [8, 11],
    engine: 'emergence',
    secondaryEngines: ['mystery'],
    lens: 'other',
    toy: null,
    play5:
      'The child drops two ripples the right distance apart to make a line of dead-still water and parks a cork there to watch it rest, a rule found by crossing rings that one ring could never show.',
  },
  {
    id: 'emergence-12',
    name: 'Tipping Grains',
    loop: 'The child drips one grain at a time onto a grid of cells; a cell holding four grains tips one to each neighbour, and the tipping can run on across the grid in a slide of colour.',
    verb: 'drip',
    ageBand: [10, 12],
    engine: 'emergence',
    secondaryEngines: ['expression'],
    lens: 'other',
    toy: null,
    play5:
      'The child reads which cells are one grain from tipping and drips at the exact cell that sets off a slide ending in the symmetric shape they want, having found that the same drips in any order build the same picture.',
  },
  {
    id: 'emergence-13',
    name: 'Dust to Worlds',
    loop: 'The child stirs a cloud of dust with a held finger; the grains pull on each other and stick when they touch, so the stirred cloud clumps into a few planets circling a heavy core.',
    verb: 'stir',
    ageBand: [10, 12],
    engine: 'emergence',
    secondaryEngines: ['expression'],
    lens: 'other',
    toy: null,
    play5:
      'The child stirs slow and steady to raise a ring of small planets instead of one lump, having learned that a fast stir flings the dust apart and no stir lets it fall into a single blob.',
  },
  {
    id: 'emergence-14',
    name: 'Ring Road Ducks',
    loop: 'The child holds one duckling still for a moment in a ring of ducklings walking nose to tail; the stop spreads backward down the line as a wave of braking that comes round the ring again.',
    verb: 'stall',
    ageBand: [10, 12],
    engine: 'emergence',
    secondaryEngines: ['mastery'],
    lens: 'other',
    toy: null,
    play5:
      'The child knows a stop travels backward and fades where the ring is loose, so stalls a duckling just behind a gap to let the wave melt away and just behind a crowd to make it roll on, reading the crowding before touching.',
  },
]
