import type { IdeaDraft } from '../types.ts'

// Engine: expression. The child makes something and the world answers it in
// its own way. Every idea below has a rule the world applies to the thing made,
// and play 5 differs because the child now aims that rule on purpose.

export const ideas: readonly IdeaDraft[] = [
  {
    id: 'expression-01',
    name: 'Puddle Bloom',
    loop: 'The child holds a finger to squash a boot over a puddle and lets go to land, and a ring of water spreads as wide as the squash was deep, bounces off the rocks and the edge, and leaps into a spout wherever two rings cross.',
    verb: 'stomp',
    ageBand: [3, 6],
    engine: 'expression',
    secondaryEngines: ['emergence'],
    lens: 'physical-toy',
    toy: 'puddle-jumping',
    play5:
      'The child lands a small jump just behind a big one so the two rings cross at a spot they picked, and jumps in a ring of spots so the spouts open into a flower they meant to make, having learned that crossing rings leap and that timing sets where they meet.',
  },
  {
    id: 'expression-02',
    name: 'Whirl Blossoms',
    loop: 'The child turns a paper disc by circling a finger on its rim and taps to drip paint onto it, and each drop is flung outward into a curling streak whose length, thickness, and curl follow how close to the middle it landed and how fast the disc turns.',
    verb: 'drip',
    ageBand: [4, 7],
    engine: 'expression',
    secondaryEngines: ['combination'],
    lens: 'physical-toy',
    toy: 'spin-art',
    play5:
      'The child drips thick colours at the middle while the disc crawls, then whips it fast so the layers fan out as a starburst in the order they were dripped, a picture planned from knowing where and how fast each drip flings.',
  },
  {
    id: 'expression-03',
    name: 'Fogged Garden',
    loop: 'The child wipes a fogged window with a finger to open a garden behind it and taps to press on a bead of water, and the beads swell, roll down the wiped grooves faster than they cross fog, merge into fat drops, and leave long clear trails.',
    verb: 'wipe',
    ageBand: [3, 6],
    engine: 'expression',
    secondaryEngines: ['emergence'],
    lens: 'other',
    toy: null,
    play5:
      'The child wipes a slanted zigzag runway and presses a bead at its top so the merged drop runs the whole zigzag and draws it onto the fog, using drips as a pen instead of watching them fall.',
  },
  {
    id: 'expression-04',
    name: 'Waking Scribbles',
    loop: 'The child scribbles a line with a finger and it wakes as a small creature that walks its own line back and forth, hopping through zigzags, rolling through loops, gliding through curves, and pacing itself at the speed the line was drawn.',
    verb: 'scribble',
    ageBand: [3, 6],
    engine: 'expression',
    secondaryEngines: ['mystery'],
    lens: 'other',
    toy: null,
    play5:
      'The child draws slowly through zigzags and fast down a straight so the creature hops with care and then bolts, and ends on a loop to send it spinning, having found that the line shape sets the gait and the drawing speed sets the pace.',
  },
  {
    id: 'expression-05',
    name: 'Slump Castles',
    loop: 'The child drags to plough and heap sand and sprinkles water from a bucket, and damp sand holds steep walls, then dries out and slumps to a gentle slope, so towers settle into ridges and rings by themselves.',
    verb: 'heap',
    ageBand: [5, 8],
    engine: 'expression',
    secondaryEngines: ['emergence'],
    lens: 'physical-toy',
    toy: 'sandpit',
    play5:
      'The child builds with the drying in mind, a wet core under a dry skin or a wet ring wall around a pit, so the slump finishes an even crater rim or a saddle between two peaks that hands alone could not push into place on play 1.',
  },
  {
    id: 'expression-06',
    name: 'Inkleaf Creek',
    loop: 'The child sets stones in a stream and taps to launch ink-dipped leaves, and the current bends around each stone, leaves circle in the eddy behind it, and every leaf paints its drifting path onto the sandy bed.',
    verb: 'coax',
    ageBand: [5, 8],
    engine: 'expression',
    secondaryEngines: ['emergence'],
    lens: 'physical-toy',
    toy: 'leaf-boats',
    play5:
      'The child sets two stones a leaf-width apart so a leaf is caught in the eddy and paints a coil, then frees it with a third stone to trail off as a comma, choosing stones by where each eddy sits to paint a shape instead of watching leaves drift.',
  },
  {
    id: 'expression-07',
    name: 'Tipping Cups',
    loop: 'The child drags to hang cups of any size on a wall and turns on the tap, and each cup fills to its brim, tips, and pours into whatever hangs below, so the cups flash a rhythm of waits and tips that the arrangement decides.',
    verb: 'perch',
    ageBand: [6, 9],
    engine: 'expression',
    secondaryEngines: ['emergence'],
    lens: 'physical-toy',
    toy: 'water-play',
    play5:
      'The child hangs a small cup so its pour lands just as a nearly full cup below is topping up, making a quick double tip on purpose, having learned that a cup size sets its wait and where it hangs sets when its pour arrives.',
  },
  {
    id: 'expression-08',
    name: 'Trellis Twist',
    loop: 'The child props sticks, upright or slanted, around a seedling in a sunny garden, and the vine grows toward the light, twines up any stick it meets head-on, and opens a flower each time it wraps a full turn.',
    verb: 'prop',
    ageBand: [5, 8],
    engine: 'expression',
    secondaryEngines: ['other-minds'],
    lens: 'other',
    toy: null,
    play5:
      'The child props a short stick spiral and a tall pole beyond it so the vine coils into a ring of flowers and then climbs on, having learned that it only climbs what it meets head-on and blooms on each wrap.',
  },
  {
    id: 'expression-09',
    name: 'Singing Plate',
    loop: 'The child pours a pinch of sand onto a square plate and slides a finger along a pitch bar, and at certain hidden tones the plate shivers and the sand hops off the shaking places and settles into lines, stars, and rings, while in-between tones leave it still.',
    verb: 'tune',
    ageBand: [8, 11],
    engine: 'expression',
    secondaryEngines: ['mystery'],
    lens: 'other',
    toy: null,
    play5:
      'The child chains three tones in an order that walks the sand from a ring to a star to a cross, a mandala only that order makes, having learned the quiet lines of each tone and that the next tone scatters only the sand that sits on its shaking places.',
  },
  {
    id: 'expression-10',
    name: 'Stone Harbour',
    loop: 'The child taps a shore to raise stones one at a time, and each stone turns itself into a hut, tower, arch, stair, or lighthouse depending on what stands beside and beneath it.',
    verb: 'raise',
    ageBand: [8, 11],
    engine: 'expression',
    secondaryEngines: ['combination', 'mystery'],
    lens: 'other',
    toy: null,
    play5:
      'The child lays out two towers with a one-stone gap and a stone at the edge of the water so the arch and the lighthouse appear where they planned a harbour with a bridge, having learned which neighbours turn a stone into which piece.',
  },
  {
    id: 'expression-11',
    name: 'Whittled Wheels',
    loop: 'The child whittles chips off a wooden disc with a finger and drags its axle peg to a new spot, then lets the wheel roll down a bumpy path, where its shape decides whether it glides, hops, or lurches and its axle draws a track behind it.',
    verb: 'whittle',
    ageBand: [7, 10],
    engine: 'expression',
    secondaryEngines: ['rule-play'],
    lens: 'other',
    toy: null,
    play5:
      'The child whittles a slightly egg-shaped wheel and moves the peg off-centre so it trundles with a hop that clears the fence and its axle draws a smooth wave, having learned how corners, flats, and where the peg sits change the ride.',
  },
  {
    id: 'expression-12',
    name: 'Pendulum Pen',
    loop: 'The child slides a weight up or down each of two rods, pulls the rods back to set their swing, and lets go, and a pen on the swinging table draws a looping knot that slowly shrinks into a spiral.',
    verb: 'pluck',
    ageBand: [10, 12],
    engine: 'expression',
    secondaryEngines: ['mastery'],
    lens: 'other',
    toy: null,
    play5:
      'The child sets the weights to a two-to-three swing and lets one rod go a moment after the other to draw the clover knot they aimed at, saying how many petals it will have from the weights before letting go.',
  },
  {
    id: 'expression-13',
    name: 'Wired Seasons',
    loop: 'The child snips a branch tip or drags a wire around a limb, then taps to let a season pass, and a cut branch sprouts two buds below the cut, wired limbs grow the way they were bent, and limbs starved of light drop away.',
    verb: 'prune',
    ageBand: [10, 12],
    engine: 'expression',
    secondaryEngines: ['emergence'],
    lens: 'other',
    toy: null,
    play5:
      'The child cuts the leader early and wires two low limbs outward to grow the windswept cascade they pictured, knowing that a cut forks the growth, a wire sets its heading, and shaded limbs die.',
  },
  {
    id: 'expression-14',
    name: 'Rain Shadow',
    loop: 'The child drags to shove ridges up out of a flat island and holds to sink bays, and clouds blow in from one edge, drop their rain on the windward slopes, feed rivers that run down to the sea, and leave the far side of every range dry and sandy.',
    verb: 'shove',
    ageBand: [10, 12],
    engine: 'expression',
    secondaryEngines: ['emergence'],
    lens: 'other',
    toy: null,
    play5:
      'The child shoves a range across the wind to dry out the valley behind it and bends the one river round the end of the range to reach the sea, a world with a desert and a green coast they aimed for, having learned that rain falls on the windward side.',
  },
]
