import type { IdeaDraft } from '../types.ts'

// Mastery shard: loops whose skill (timing, aim, balance, control) has a
// ceiling above what a first try shows. Play 5 differs by a technique the
// child found or an outcome they now anticipate, not by a bigger number.

export const ideas: readonly IdeaDraft[] = [
  {
    id: 'mastery-01',
    name: 'Stubborn Balloon',
    loop: 'A slow balloon sinks through the field and the child pats it: a pat under the middle sends it straight up, a pat off to one side spins it so it curls that way, a finger held beneath cradles it, and a bear across the field reaches up and bats it back when it floats over.',
    verb: 'pat',
    ageBand: [2, 5],
    engine: 'mastery',
    secondaryEngines: ['mystery'],
    lens: 'physical-toy',
    toy: 'balloon-keepy-uppy',
    play5:
      'The child now pats beside the balloon on purpose to curl it across the field to the waiting bear, having found that off-centre pats spin it, where on play 1 every pat only sent it up.',
  },
  {
    id: 'mastery-02',
    name: 'Chant Rope',
    loop: 'Two turner creatures swing a rope through a slow-slow-quick-quick chant, and the child holds a crouching jumper and lets go to leap, the length of the hold deciding the hang time.',
    verb: 'skip',
    ageBand: [4, 7],
    engine: 'mastery',
    secondaryEngines: ['other-minds'],
    lens: 'physical-toy',
    toy: 'jump-rope',
    play5:
      'The child has learned the chant the turners keep and leaps once with a long held hang over both quick swings, landing back on the slow beat, instead of chasing each swing one at a time.',
  },
  {
    id: 'mastery-03',
    name: 'To the Brim',
    loop: 'The child drags a jug to tilt it over a row of cups: nothing flows until the lip passes a tipping point, then it gushes on for a beat after they ease back.',
    verb: 'tilt',
    ageBand: [3, 6],
    engine: 'mastery',
    secondaryEngines: [],
    lens: 'other',
    toy: null,
    play5:
      'The child now creeps the jug to the tipping point, holds, and eases back before the gush arrives, so even the smallest cup fills to the brim without a spill, having felt where the gush begins.',
  },
  {
    id: 'mastery-04',
    name: 'Where Puppy Goes',
    loop: 'A puppy trots back and forth along the far side and the child tosses a ball toward it; a ball that lands where the puppy was gets chased and missed, and a ball that lands where it is going is caught mid-stride.',
    verb: 'toss',
    ageBand: [3, 6],
    engine: 'mastery',
    secondaryEngines: ['other-minds'],
    lens: 'other',
    toy: null,
    play5:
      'The child now aims ahead of the trotting puppy and times the toss to its pause at each turn, having read its habit of trotting, pausing, then doubling back, and catches it where it is going.',
  },
  {
    id: 'mastery-05',
    name: 'Toes in Clouds',
    loop: 'The child holds to stretch the legs of the rider out as the seat swings forward and lets go as it swings back, so the arc grows only when the pumping is in step, and a tap at the top of the arc lets go and sends the rider flying.',
    verb: 'pump',
    ageBand: [5, 8],
    engine: 'mastery',
    secondaryEngines: [],
    lens: 'physical-toy',
    toy: 'swing',
    play5:
      'The child now waits at the forward peak of a wide arc and lets go so the rider sails onto the far hill, having learned that where in the arc they release decides where the rider lands.',
  },
  {
    id: 'mastery-06',
    name: 'Quiet Fingers',
    loop: 'A heap of long sticks lies criss-crossed and the child drags one out: a slow drag leaves its neighbours still, a hurried one shoves them, and pressing one end of a stick tips the other end up.',
    verb: 'ease',
    ageBand: [5, 8],
    engine: 'mastery',
    secondaryEngines: ['emergence'],
    lens: 'physical-toy',
    toy: 'pick-up-sticks',
    play5:
      'The child now reads which sticks carry the weight of others, presses one end to tip a pinned stick free, and draws it out at a creep, an approach they had no reason to try on play 1.',
  },
  {
    id: 'mastery-07',
    name: 'Chalk Hop',
    loop: 'The child slides a pebble onto a chalk square, taps a hop path down the squares (one foot on singles, two on pairs, skipping the pebble square), and holds to bend for the pebble on the way back while one-foot wobble builds.',
    verb: 'hop',
    ageBand: [5, 8],
    engine: 'mastery',
    secondaryEngines: [],
    lens: 'physical-toy',
    toy: 'hopscotch',
    play5:
      'The child now hops in one unbroken beat that keeps the one-foot wobble low and slides the pebble to the square after a two-foot rest, so the bend on the way back is steady, a link between throw and hop they could not see on play 1.',
  },
  {
    id: 'mastery-08',
    name: 'Soft Hands',
    loop: 'A hen on a shelf drops eggs and the child drags a basket beneath: a basket held still cracks the egg, but one that sinks with the falling egg brings it to rest whole.',
    verb: 'cushion',
    ageBand: [5, 8],
    engine: 'mastery',
    secondaryEngines: ['mystery'],
    lens: 'other',
    toy: null,
    play5:
      'The child now meets the egg at the top and rides it down with the basket to bring it to rest, having found that giving way with the fall is what keeps it whole.',
  },
  {
    id: 'mastery-09',
    name: 'Flat Stone',
    loop: 'The child swipes a flat stone low across a pond: a shallow, quick swipe skips it in shrinking hops and a steep one sinks it in a single plop, with rings spreading wherever it touches.',
    verb: 'skim',
    ageBand: [7, 10],
    engine: 'mastery',
    secondaryEngines: [],
    lens: 'other',
    toy: null,
    play5:
      'The child now swipes low and long so the last small skip lands on the far lily pad and the frog there hops, having learned that the angle of the swipe sets where the skips end.',
  },
  {
    id: 'mastery-10',
    name: 'Snapping Ribbon',
    loop: 'The child drags a wand with a long ribbon trailing behind it, and a quick flick and stop sends a wave down the ribbon so its tip snaps out through the hoops drifting nearby.',
    verb: 'whip',
    ageBand: [7, 10],
    engine: 'mastery',
    secondaryEngines: ['emergence'],
    lens: 'other',
    toy: null,
    play5:
      'The child now flicks and stops short so the tip overshoots through a hoop far from the wand, allowing for the wave travel time instead of dragging the whole ribbon over to it.',
  },
  {
    id: 'mastery-11',
    name: 'Reed Canoe',
    loop: 'The child taps the left or right of a canoe to dip a paddle on that side, each stroke pushing it forward and turning it away, so alternating sides runs straight, and a held touch drags the water and swings it round in place.',
    verb: 'paddle',
    ageBand: [7, 10],
    engine: 'mastery',
    secondaryEngines: [],
    lens: 'other',
    toy: null,
    play5:
      'The child now spaces strokes to hold a straight line across the drifting current and holds one side to spin the canoe on the spot into the narrow reed cove, moves they had no reason to try while zigzagging on play 1.',
  },
  {
    id: 'mastery-12',
    name: 'Broom on a Fingertip',
    loop: 'A tall broom stands on the fingertip point the child drags and leans further the more it tilts, so the child slides the fingertip under the lean to keep it upright and walk it across the field.',
    verb: 'balance',
    ageBand: [10, 12],
    engine: 'mastery',
    secondaryEngines: ['mystery'],
    lens: 'other',
    toy: null,
    play5:
      'The child now moves under the broom before a lean is visible instead of chasing it, and shakes a hanging broom up to standing, a trick found by fiddling on an earlier play.',
  },
  {
    id: 'mastery-13',
    name: 'Sleeping Yo-Yo',
    loop: 'The child throws a yo-yo down its string by dragging the hand down and tugs it back by dragging up; a hard enough throw leaves it spinning at the bottom, and it climbs home only if the tug comes while it still spins.',
    verb: 'tug',
    ageBand: [10, 12],
    engine: 'mastery',
    secondaryEngines: ['mystery'],
    lens: 'other',
    toy: null,
    play5:
      'The child now throws hard enough to make it sleep and uses the spinning wait to swing it out sideways and around before tugging it home, a use of the sleeper they could not find while it always came straight back.',
  },
  {
    id: 'mastery-14',
    name: 'Bank Shot',
    loop: 'The child drags back from a ball to set its aim and power and touches a point on the ball to set its spin; it rebounds off the cushions toward a pocket, and the spin bends how it leaves each cushion.',
    verb: 'carom',
    ageBand: [10, 12],
    engine: 'mastery',
    secondaryEngines: ['rule-play'],
    lens: 'other',
    toy: null,
    play5:
      'The child now picks the touch point on purpose, drawing the ball back to stop it dead after a hit or driving it on with follow, and banks round a blocker with spin that the plain angle rule cannot give.',
  },
]
