import type { IdeaDraft } from '../types.ts'

export const ideas: readonly IdeaDraft[] = [
  {
    id: 'mystery-01',
    name: 'What the Owl Sees',
    loop: 'The child drags a chick into a leafy meadow and lets go, and an owl sweeps its gaze across the field and either swoops on the chick or glides past, by sight rules nobody shows.',
    verb: 'tuck',
    ageBand: [4, 7],
    engine: 'mystery',
    secondaryEngines: ['other-minds', 'rule-play'],
    lens: 'physical-toy',
    toy: 'hide-and-seek',
    play5:
      'The child arrives knowing the owl misses anything that holds still, so they hide the chick at once and then test on purpose whether matching a patch colour or sitting behind reeds also fools it, the blind spot they have not found.',
  },
  {
    id: 'mystery-02',
    name: 'Shy Garden',
    loop: 'The child touches sleepy buds and shy creatures in a garden, and each answers only to one kind of touch (a slow hold, a quick pat, a stroke, a circle) by blooming, hiding, or bouncing.',
    verb: 'coax',
    ageBand: [2, 5],
    engine: 'mystery',
    secondaryEngines: ['combination'],
    lens: 'other',
    toy: null,
    play5:
      'The child greets each kind of plant with the touch they learned for it, calming a startled bud with a stroke before the hold that opens it, and spends the visit on the one kind that has never answered.',
  },
  {
    id: 'mystery-03',
    name: 'Thump and Dig',
    loop: 'The child thumps the ground and the earth shivers harder the nearer something is buried, and a long hold digs it up; each kind of buried thing lies beside its own landmark, worms by puddles, bones by fences, acorns in tree shade.',
    verb: 'thump',
    ageBand: [3, 6],
    engine: 'mystery',
    secondaryEngines: ['variation'],
    lens: 'other',
    toy: null,
    play5:
      'The child stops thumping at random, walks to a fence or a puddle first and thumps beside it, and works out where the one kind they never found likes to be buried.',
  },
  {
    id: 'mystery-04',
    name: 'Lantern Colours',
    loop: 'The child drags a lantern over a dark meadow and taps it to change its colour, and scribbles and creatures painted there appear, vanish, or change with the light by a colour rule nobody states.',
    verb: 'shine',
    ageBand: [3, 6],
    engine: 'mystery',
    secondaryEngines: ['rule-play'],
    lens: 'other',
    toy: null,
    play5:
      'The child knows a painted thing vanishes under its own colour of light, so they shine the wrong colour on purpose to wipe out decoy scribbles and uncover the creature hiding beneath them.',
  },
  {
    id: 'mystery-05',
    name: 'Under the Cloth',
    loop: 'The child sweeps a hand magnet over a blank cloth, tapping to flip its pole, and beads on the cloth clump toward or ring away from magnets and iron plates hidden underneath while the hand magnet lurches and snaps.',
    verb: 'dowse',
    ageBand: [6, 9],
    engine: 'mystery',
    secondaryEngines: ['variation'],
    lens: 'physical-toy',
    toy: 'magnets',
    play5:
      'The child reads a clump versus a ring at a glance, flips the pole first to tell a magnet from an iron plate, and goes after the spot where two hidden magnets sit close and half cancel each other.',
  },
  {
    id: 'mystery-06',
    name: 'Shadows Tell Lies',
    loop: 'The child twists a cone, a cube, and a rod between a lamp and a wall and watches each shadow change with the turn and the distance, and sleepers painted on the wall wake for silhouettes the child was never shown.',
    verb: 'twist',
    ageBand: [5, 8],
    engine: 'mystery',
    secondaryEngines: ['combination'],
    lens: 'physical-toy',
    toy: 'shadow-puppets',
    play5:
      'The child knows a cone end-on casts a circle and a rod end-on casts a dot, so they disguise one solid as another shape on purpose and go after the sleeper that needs two shadows overlapped.',
  },
  {
    id: 'mystery-07',
    name: 'Prints in the Mist',
    loop: 'Footprints appear one at a time across a misty field from an unseen walker, the child taps where it will step next, and the walker shows itself when the child has read its habit right.',
    verb: 'track',
    ageBand: [6, 9],
    engine: 'mystery',
    secondaryEngines: ['other-minds'],
    lens: 'other',
    toy: null,
    play5:
      'The child tells from the first three prints which walker this is (one curves to the nearest bush, another bounds in straight leaps) and taps ahead of it, then studies the trail of the one habit they have not decoded.',
  },
  {
    id: 'mystery-08',
    name: 'Something Rattles',
    loop: 'The child drags a sealed box back and forth so hidden things slide and clunk inside and jerk the box around, and a long hold opens the lid to check the guess.',
    verb: 'jostle',
    ageBand: [5, 8],
    engine: 'mystery',
    secondaryEngines: ['emergence'],
    lens: 'other',
    toy: null,
    play5:
      'The child recognises the lurch of each kind of content (a heavy ball drags one way, marbles skitter, a sticky blob stops dead) and opens the lid only to confirm, saving careful poking for the box where two kinds blur together.',
  },
  {
    id: 'mystery-09',
    name: 'The Answering Can',
    loop: 'The child pulls a tin can out until its string is taut and knocks on it, and a hidden friend answers down the string with a rhythm changed by a rule the child must work out, while slack leaves the line dead.',
    verb: 'knock',
    ageBand: [7, 10],
    engine: 'mystery',
    secondaryEngines: ['rule-play'],
    lens: 'physical-toy',
    toy: 'tin-can-telephone',
    play5:
      'The child sends one lone knock and then two spaced knocks to test a guess on purpose, tells within a few exchanges whether this friend echoes, reverses, or doubles, and seeks out the friend that stacks two rules together.',
  },
  {
    id: 'mystery-10',
    name: 'Speak Beast',
    loop: 'The child scrawls a squiggle in front of a big beast that answers with a move, and which parts of the squiggle it reads (its turning, its peak, whether it closes into a loop) are never shown.',
    verb: 'scrawl',
    ageBand: [7, 10],
    engine: 'mystery',
    secondaryEngines: ['expression', 'combination'],
    lens: 'other',
    toy: null,
    play5:
      'The child draws one squiggle to make the beast turn left and then leap the stream because they know which feature it reads for each, and probes the one feature that changes how the move ends.',
  },
  {
    id: 'mystery-11',
    name: 'Pond Pecking Order',
    loop: 'The child releases swimmers into a pond one or two at a time and watches which chase, flee, ignore, or crowd each other, then works out the hidden pecking order to keep a favourite swimmer safe.',
    verb: 'release',
    ageBand: [8, 11],
    engine: 'mystery',
    secondaryEngines: ['other-minds', 'emergence'],
    lens: 'other',
    toy: null,
    play5:
      'The child knows big eats small holds except for one odd species each visit, so they release the suspect beside a large swimmer first to find the exception, then use it to shield a favourite.',
  },
  {
    id: 'mystery-12',
    name: 'Where the Mirrors Stand',
    loop: 'The child slides one bead across a round table while its mirrored and rotated copies move with it, and the hidden mirror lines show only when a bead meets its own twin and the two fuse into one shape.',
    verb: 'slide',
    ageBand: [10, 12],
    engine: 'mystery',
    secondaryEngines: ['variation'],
    lens: 'physical-toy',
    toy: 'kaleidoscope',
    play5:
      'The child reads the fold count from the first bead copies, aims twin meetings to expose the mirror lines on purpose, and hunts the odd mirror that turns its copy instead of flipping it.',
  },
  {
    id: 'mystery-13',
    name: 'The Sulking Lamp',
    loop: 'The child arranges coloured shapes on a stage, and a lamp above glows warm when the arrangement obeys a rule nobody states and sulks dim when it does not.',
    verb: 'arrange',
    ageBand: [10, 12],
    engine: 'mystery',
    secondaryEngines: ['variation'],
    lens: 'other',
    toy: null,
    play5:
      'The child builds a pair of near-identical arrangements that differ in one thing to isolate the rule, names its type after two tests, and goes after the rules that only hold when two shapes touch.',
  },
  {
    id: 'mystery-14',
    name: 'Blind Bumpers',
    loop: 'The child launches a marble into a sealed square from any edge, hidden bumpers inside bounce it out somewhere else or swallow it, and the child works out where the bumpers sit and marks them.',
    verb: 'probe',
    ageBand: [10, 12],
    engine: 'mystery',
    secondaryEngines: ['variation'],
    lens: 'other',
    toy: null,
    play5:
      'The child fires from two edges to triangulate and knows a marble that returns to its own doorway means a head-on hit, so they go after the bumper tucked in a corner that only a grazing shot can reveal.',
  },
]
