import type { IdeaDraft } from '../types.ts'

// Engine: other-minds. Every idea here has characters with their own habits,
// nerve, or beliefs. The habits are fixed per character, so what play 5 shows
// is the child reading them, not the world getting bigger.

export const ideas: readonly IdeaDraft[] = [
  {
    id: 'other-minds-01',
    name: 'Blanket Beats',
    loop: 'You drag a blanket over a creature and its lump wiggles to a private count until it pops out, and it bursts into a dance only when you whip the blanket off right on its beat.',
    verb: 'drape',
    ageBand: [2, 4],
    engine: 'other-minds',
    secondaryEngines: ['mastery'],
    lens: 'physical-toy',
    toy: 'peekaboo',
    play5:
      'The child knows the mole peeks after two beats, the owl after five, and the fox slips out under the next blanket, so they lift each blanket on that creature\'s own beat and look for the fox where it will reappear.',
  },
  {
    id: 'other-minds-02',
    name: 'Dawdle Parade',
    loop: 'You drag a mother duck across a meadow and each duckling trails her by its own habit, one dawdles at flowers, one cuts corners, one follows only the duckling ahead, so the line stretches, snarls, and reforms.',
    verb: 'lead',
    ageBand: [2, 5],
    engine: 'other-minds',
    secondaryEngines: ['emergence'],
    lens: 'other',
    toy: null,
    play5:
      'The child knows the dawdler stalls at flowers and the corner-cutter jumps the line on any bend, so they walk a loop on purpose to shuffle the corner-cutter to the front and steer wide of the flowers.',
  },
  {
    id: 'other-minds-03',
    name: 'Shy Sparks',
    loop: 'You hold a still cupped hand among drifting, blinking fireflies and each lands in it when its own nerve allows, the nervous ones only beside bold ones already resting there, and lifting your finger lets them all go.',
    verb: 'cup',
    ageBand: [3, 6],
    engine: 'other-minds',
    secondaryEngines: ['mystery'],
    lens: 'physical-toy',
    toy: 'firefly-jar',
    play5:
      'The child knows which firefly lands at once and which only settles beside others, so they hold still for the bold ones first and end up cupping the shy one that never landed on play 1.',
  },
  {
    id: 'other-minds-04',
    name: 'Grumble and Giggle',
    loop: 'You stroke, hold, or scribble on round blobs whose faces show a mood, and each blob passes its mood to its neighbours in its own way: one boils over when crowded, one weeps when alone, one spreads giggles.',
    verb: 'soothe',
    ageBand: [4, 7],
    engine: 'other-minds',
    secondaryEngines: ['emergence'],
    lens: 'other',
    toy: null,
    play5:
      'The child knows the red one boils when squeezed between two others and the blue one cries alone, so they park the red one at the edge and seat a giggler beside the crier before the mood can spread.',
  },
  {
    id: 'other-minds-05',
    name: 'Pass the Glow',
    loop: 'You drag the glowing It after the others, and when you touch one the glow and your control jump into it while the old It scampers away the way it always does.',
    verb: 'chase',
    ageBand: [5, 8],
    engine: 'other-minds',
    secondaryEngines: ['mastery'],
    lens: 'physical-toy',
    toy: 'tag',
    play5:
      'The child knows the hare bolts then doubles back, the tortoise freezes, and the magpie runs toward whoever tagged it, so they choose whose body to be next and corner each runner by its habit.',
  },
  {
    id: 'other-minds-06',
    name: 'Rope Crew',
    loop: 'You line creatures up on a rope and call a heave, and each pulls by its own habit, the bear heaves late, the kitten burns out, the goat drops the rope for a butterfly, while the knot creeps toward whichever crew heaves in step.',
    verb: 'rally',
    ageBand: [5, 8],
    engine: 'other-minds',
    secondaryEngines: ['mastery', 'combination'],
    lens: 'physical-toy',
    toy: 'tug-of-war',
    play5:
      'The child knows the bear lands half a beat after the call and the kitten tires quickly, so they put the kitten last, call early for the bear, and time the heaves for when the rival crew is catching its breath.',
  },
  {
    id: 'other-minds-07',
    name: 'Wiggle Before Pounce',
    loop: 'You wave a glowing dot for cats that stalk, wiggle, and pounce by their own habits: one leaps to where the dot will be, one only sprints after a long stare, and a cat that keeps missing sulks off.',
    verb: 'tease',
    ageBand: [5, 8],
    engine: 'other-minds',
    secondaryEngines: ['rule-play'],
    lens: 'other',
    toy: null,
    play5:
      'The child knows each cat\'s tell before the pounce, so they freeze the dot mid-wiggle to make the pouncer leap short and let the watcher catch it once to head off its sulk.',
  },
  {
    id: 'other-minds-08',
    name: 'Pecking Order',
    loop: 'You sprinkle crumbs on a pond where the fish rank each other: the big carp bullies everyone off each crumb, the middle fish nudge the small ones, and the smallest darts in whenever the bully turns away.',
    verb: 'sprinkle',
    ageBand: [6, 9],
    engine: 'other-minds',
    secondaryEngines: ['emergence'],
    lens: 'other',
    toy: null,
    play5:
      'The child knows who bullies whom, so they lure the big carp to a far corner with a decoy scatter and drop the real crumbs where the shy minnow can eat undisturbed.',
  },
  {
    id: 'other-minds-09',
    name: 'Clap Back',
    loop: 'A hand creature claps a short pattern at its own tempo and you clap back on two pads, and it answers however you play: the hare speeds up while you keep pace, the owl adds a step after two clean answers, the magpie copies you with a twist.',
    verb: 'answer',
    ageBand: [7, 10],
    engine: 'other-minds',
    secondaryEngines: ['mastery', 'expression'],
    lens: 'physical-toy',
    toy: 'clapping-games',
    play5:
      'The child knows the hare overreaches if you keep pace and the magpie repeats whatever you play, so they pace the hare into a stumble and feed the magpie a rhythm to watch it twisted their way.',
  },
  {
    id: 'other-minds-10',
    name: 'Sly Paws',
    loop: 'You and a creature each hide a pebble in one paw and guess the other one, and every creature hides and guesses by its own habit while reading yours.',
    verb: 'bluff',
    ageBand: [8, 11],
    engine: 'other-minds',
    secondaryEngines: ['rule-play'],
    lens: 'other',
    toy: null,
    play5:
      'The child knows the fox switches after a miss and the owl bets you will repeat, so they feed the owl a false habit for three rounds and break it on the fourth.',
  },
  {
    id: 'other-minds-11',
    name: 'Last Place Seen',
    loop: 'You shift a treasure between hollow logs while the guards look away, and each guard walks to the log where it last saw the treasure, not where it is, and rechecks by its own habit.',
    verb: 'filch',
    ageBand: [8, 11],
    engine: 'other-minds',
    secondaryEngines: ['rule-play', 'mystery'],
    lens: 'other',
    toy: null,
    play5:
      'The child knows the goose only trusts its last sighting and the hound sniffs out a move after a pause, so they shift the treasure while the goose stares at the old log and the hound is still looking away.',
  },
  {
    id: 'other-minds-12',
    name: 'Fox in Fleece',
    loop: 'You steer a fox pup through a moving flock, and it stays unnoticed only while it moves like the sheep around it, grazing, pausing, and drifting in step, as a sheepdog scans for whoever moves oddly.',
    verb: 'blend',
    ageBand: [10, 12],
    engine: 'other-minds',
    secondaryEngines: ['emergence', 'mastery'],
    lens: 'other',
    toy: null,
    play5:
      'The child knows the sheepdog sweeps left to right and glances away at the pond, and reads which sheep pause and which drift, so they join the pausers and cross the open gap the moment the dog looks away.',
  },
  {
    id: 'other-minds-13',
    name: 'Word Gets Round',
    loop: 'You give berries to animals in a ring or snatch them away, and each animal remembers and tells its friends in its own gossip habit, so a kindness or a theft travels the ring along the paths each gossip likes.',
    verb: 'befriend',
    ageBand: [10, 12],
    engine: 'other-minds',
    secondaryEngines: ['emergence'],
    lens: 'other',
    toy: null,
    play5:
      'The child knows the jay tells everyone at once, the mole tells no one, and the owl only repeats what it saw, so they earn the jay\'s goodwill first and win the shy badger through a friend\'s word.',
  },
  {
    id: 'other-minds-14',
    name: 'Chill in the Parlor',
    loop: 'You drift a cold spot through a party of guests and each reacts by its own nerve: the screamer flees and circles back, the brave one marches at it, the skeptic ignores it until you rattle a vase.',
    verb: 'haunt',
    ageBand: [10, 12],
    engine: 'other-minds',
    secondaryEngines: ['rule-play'],
    lens: 'other',
    toy: null,
    play5:
      'The child knows the screamer\'s shriek pulls the skeptic\'s attention and the brave one always backs off after a few steps, so they use one guest\'s panic to send another guest into the corner they wanted.',
  },
]
