import type { IdeaDraft } from '../types.ts'

// Rule-play: a rule of the world the child can bend, invert, or exploit.
// In every idea below the plain use of the rule works for something near, and
// the bent use reaches something the plain use cannot.

export const ideas: readonly IdeaDraft[] = [
  {
    id: 'rule-play-01',
    name: 'The Wandering Pivot',
    loop: 'The child drags a heavy bear and a tiny mouse onto a plank and slides its pivot along it, and the plank tips by leverage, so the mouse on the long arm can swing the bear up to the honey ledge.',
    verb: 'slide',
    ageBand: [4, 7],
    engine: 'rule-play',
    secondaryEngines: ['mystery'],
    lens: 'physical-toy',
    toy: 'see-saw',
    play5:
      'The child slides the pivot right up against the bear on purpose, so the mouse is the one who goes down and the heavy bear rides up to a ledge that a plain balanced plank never reached.',
  },
  {
    id: 'rule-play-02',
    name: 'Upside-Down Puddle',
    loop: 'The child holds a finger down to open a bubble where gravity runs upside down, and pebbles and fluffy chicks that fall into it float up and out the top.',
    verb: 'loft',
    ageBand: [3, 6],
    engine: 'rule-play',
    secondaryEngines: [],
    lens: 'other',
    toy: null,
    play5:
      'The child opens the bubble under a chick at the peak of its hop, so it is carried up and out sideways onto the nest ledge, placing the bubble where the arc needs it instead of only watching things rise.',
  },
  {
    id: 'rule-play-03',
    name: 'Timber Across the Creek',
    loop: 'The child stands tall blocks on end at a creek bank and holds a finger against one to tip it, and it falls across the water to become the bridge a wooden doll rolls over.',
    verb: 'topple',
    ageBand: [5, 8],
    engine: 'rule-play',
    secondaryEngines: ['mastery'],
    lens: 'physical-toy',
    toy: 'wooden-blocks',
    play5:
      'The child sets a block with its foot right at the bank so its fall lands on the far bank, then stands a second block on the first one\'s tip and fells that too, crossing water no single block spans.',
  },
  {
    id: 'rule-play-04',
    name: 'Who Backs Off',
    loop: 'The child sends animals onto a one-lane bridge from both banks, and when two meet the scarier one makes the other back off, but scariness runs in a circle: the cat scares the mouse, the mouse scares the elephant, the elephant scares the cat.',
    verb: 'usher',
    ageBand: [5, 8],
    engine: 'rule-play',
    secondaryEngines: ['other-minds'],
    lens: 'other',
    toy: null,
    play5:
      'The child sends the mouse onto the bridge first to clear the elephant off it, and holds the cat back until the elephant is gone, using the scare circle on purpose to get past an order that the biggest-goes-first habit leaves jammed.',
  },
  {
    id: 'rule-play-05',
    name: 'Wrong Shape Stays',
    loop: 'A spout drips seeds onto a board of shaped holes, and the child sets shapes over the holes, so a matching shape drops through while a wrong one stays put and plugs its hole, steering the seeds to the creature under the last open one.',
    verb: 'plug',
    ageBand: [3, 6],
    engine: 'rule-play',
    secondaryEngines: [],
    lens: 'physical-toy',
    toy: 'shape-sorter',
    play5:
      'The child covers three holes with shapes that do not fit them, on purpose, so every seed reaches the one sleepy creature they picked, treating the misfit as the tool.',
  },
  {
    id: 'rule-play-06',
    name: 'Tail-First Train',
    loop: 'The child drags the head of a long caterpillar train through winding paths and taps its tail to make the tail the new head, so the train can back out of dead ends it is too long to turn around in.',
    verb: 'reverse',
    ageBand: [4, 7],
    engine: 'rule-play',
    secondaryEngines: [],
    lens: 'other',
    toy: null,
    play5:
      'The child drives the whole train into a dead-end nook on purpose to reach the leaf at its end, then swaps head and tail to back out, using the swap to reach a place a one-way train would be stuck in.',
  },
  {
    id: 'rule-play-07',
    name: 'Jelly Halves',
    loop: 'The child pinches a jelly blob in two and drags the halves apart, and a small half squeezes through a crack that a whole jelly cannot, and the halves join back into one when pushed together to shove a heavy stone.',
    verb: 'pinch',
    ageBand: [5, 8],
    engine: 'rule-play',
    secondaryEngines: [],
    lens: 'other',
    toy: null,
    play5:
      'The child splits the jelly before the crack on purpose, sends one half through, and rejoins on the far side so the whole jelly is there to push the stone, using splitting to be small for the gap and whole for the stone.',
  },
  {
    id: 'rule-play-08',
    name: 'Bump Meets Bump',
    loop: 'The child flicks one end of a long coil to send a bump down it, and a bump that meets another bump grows tall enough to ring a bell that no single flick reaches, and a bump bounces back off the pinned far end.',
    verb: 'flick',
    ageBand: [6, 9],
    engine: 'rule-play',
    secondaryEngines: ['mastery'],
    lens: 'physical-toy',
    toy: 'slinky',
    play5:
      'The child times a second flick to meet the first bump as it bounces back off the pinned end, choosing where the two meet so they add up at the bell.',
  },
  {
    id: 'rule-play-09',
    name: 'Loose Rows',
    loop: 'The child jumps pegs over neighbours to remove them, and can also shove a whole row along by one hole, so a stranded peg lands beside a neighbour it can jump.',
    verb: 'shove',
    ageBand: [8, 11],
    engine: 'rule-play',
    secondaryEngines: ['mastery'],
    lens: 'physical-toy',
    toy: 'peg-solitaire',
    play5:
      'The child shoves a row on purpose to line a stranded peg up beside a partner, clearing pegs that no plain sequence of jumps could reach.',
  },
  {
    id: 'rule-play-10',
    name: 'Clanking Chasers',
    loop: 'The child steps one square at a time while every robot takes one straight step toward them, and robots that bump into each other tangle into a scrap heap that stops the others.',
    verb: 'lure',
    ageBand: [7, 10],
    engine: 'rule-play',
    secondaryEngines: ['other-minds'],
    lens: 'other',
    toy: null,
    play5:
      'The child steps to a square where the robots\' straight-line steps drive them into each other, herding the whole squad into one scrap heap on purpose instead of running from each robot.',
  },
  {
    id: 'rule-play-11',
    name: 'Ghost Holds Door',
    loop: 'The child drags a path for a small bug, and once it reaches the end a ghost bug repeats that exact path forever, standing on a plate that holds a door open while the child drags the next bug through.',
    verb: 'trace',
    ageBand: [8, 11],
    engine: 'rule-play',
    secondaryEngines: ['mastery'],
    lens: 'other',
    toy: null,
    play5:
      'The child lays down two ghosts whose loops overlap so one is always on the plate as the other steps off, keeping the door open for a bug that no single ghost could cover.',
  },
  {
    id: 'rule-play-12',
    name: 'Pushable Rules',
    loop: 'The child pushes picture tiles that spell the room\'s rules (a rock, a link mark, a wall), and pushing them into a different line changes what the rock, the wall, or the frog does for real.',
    verb: 'rewrite',
    ageBand: [10, 12],
    engine: 'rule-play',
    secondaryEngines: ['mystery'],
    lens: 'other',
    toy: null,
    play5:
      'The child breaks a rule on purpose, making the wall something the frog walks through, to cross a room that walking around it could not.',
  },
  {
    id: 'rule-play-13',
    name: 'Borrowed Gravity',
    loop: 'The child drops small planets onto a starfield and then launches a probe past them, and each planet pulls the probe toward it, so a planet can whip the probe around a wall toward a distant beacon.',
    verb: 'sling',
    ageBand: [10, 12],
    engine: 'rule-play',
    secondaryEngines: ['mastery'],
    lens: 'other',
    toy: null,
    play5:
      'The child places a planet so the probe swings tight around it and leaves with a speed a straight throw cannot give, using the swing-by to hit a beacon a direct launch falls short of.',
  },
  {
    id: 'rule-play-14',
    name: 'Crease Country',
    loop: 'The child folds a paper landscape along a dragged crease so far-apart ledges land on top of each other, and a paper creature steps across the overlap to places no flat path connects.',
    verb: 'fold',
    ageBand: [10, 12],
    engine: 'rule-play',
    secondaryEngines: ['combination'],
    lens: 'other',
    toy: null,
    play5:
      'The child picks the crease from where two ledges sit so they meet, crosses, then folds a second time from the far side to reach a spot the first fold made possible.',
  },
]
