import type { IdeaDraft } from '../types.ts'

// Engine: variation. Each session deals a new seeded world, deck, or weather,
// and the child learns the cue language that says what works in it. Every
// play-5 line is a change in what the child does or finds, never escalation.

export const ideas: readonly IdeaDraft[] = [
  {
    id: 'variation-01',
    name: 'Layer Cake Sky',
    loop: 'The child drags to run the kite holder along the ground and holds to pay out or reel in string, and the kite rides whichever wind band it floats in (left low down, right up high, dead calm between) toward a ribbon snagged on a far cloud; each sky stacks its bands differently.',
    verb: 'reel',
    ageBand: [5, 8],
    engine: 'variation',
    secondaryEngines: ['mastery'],
    lens: 'physical-toy',
    toy: 'kite',
    play5:
      'The child reads which way the drifting leaves, birds, and streaks move at each height on arrival, then hauls the kite up through one band and across into the next to reach the ribbon, a two-band route that steady running on play 1 could not find.',
  },
  {
    id: 'variation-02',
    name: 'Drafty Room Flyer',
    loop: 'The child drags fold handles for the nose, wings, and tail of a paper plane, then flings it across a room where a heater updraft, a fan gust, and a cold window sink sit in different spots each day, aiming for the basket.',
    verb: 'crease',
    ageBand: [7, 10],
    engine: 'variation',
    secondaryEngines: ['combination'],
    lens: 'physical-toy',
    toy: 'paper-airplane',
    play5:
      'The child scans the room for shimmer, ribbons, and a frosty pane before folding, then picks wide wings to ride the heater or a stiff dart to punch through the fan, choosing the fold for the room where on play 1 they tweaked one fold and hoped.',
  },
  {
    id: 'variation-03',
    name: 'Lopsided Tin Walker',
    loop: 'The child holds a big key to wind a tin walker, lets go, and it clatters toward a waiting plush along a chalk trail it draws, bending by its own lean and stumbling on cloth folds; each day the toy leans, hops, and wobbles differently.',
    verb: 'wind',
    ageBand: [4, 6],
    engine: 'variation',
    secondaryEngines: ['mystery'],
    lens: 'physical-toy',
    toy: 'wind-up-toy',
    play5:
      'The child sends the walker off once to see which way its chalk trail bends, then sets it down angled against the bend so the curve carries it onto the plush, where on play 1 every crooked walk looked like bad luck.',
  },
  {
    id: 'variation-04',
    name: 'Sun and Puddle Plot',
    loop: 'The child presses seeds of different shapes into a garden plot and holds a watering can over them, and each seed sprouts tall, wide, or odd according to the sunny, soggy, or shady patch it landed in; the patches are laid out differently every day.',
    verb: 'sow',
    ageBand: [4, 7],
    engine: 'variation',
    secondaryEngines: ['mystery', 'combination'],
    lens: 'physical-toy',
    toy: 'seed-planting',
    play5:
      'The child reads the shine, shade, and shimmer before planting, sets each seed on the patch it likes, and plants across a patch border on purpose to grow the blended flower that only turned up by accident on play 1.',
  },
  {
    id: 'variation-05',
    name: 'Restless Cards',
    loop: "The child flips two face-down cards at a time and a matched pair lifts away, but after every miss the whole table moves by that day's own shuffle (the ring turns a notch, the rows swap, the columns slide) instead of staying put.",
    verb: 'flip',
    ageBand: [5, 8],
    engine: 'variation',
    secondaryEngines: ['mystery', 'rule-play'],
    lens: 'physical-toy',
    toy: 'memory-cards',
    play5:
      "The child watches a single miss to learn how today's cards travel, then flips a card seen earlier at its new place by counting the shift, where on play 1 they hunted for where the card used to be.",
  },
  {
    id: 'variation-06',
    name: "Jug of Today's Stuff",
    loop: "The child drags a jug over sleepy cups and holds to tip it, and today's stuff (syrup, beads, feathers, or water) pours its own way, so a cup that fills makes its sleeper yawn.",
    verb: 'pour',
    ageBand: [2, 4],
    engine: 'variation',
    secondaryEngines: ['mastery'],
    lens: 'other',
    toy: null,
    play5:
      'The child knows the stuff by its look and tips, waits, or hovers to suit it before anything spills: hold long for syrup, get right over the cup for feathers, use the wide cup for bouncing beads.',
  },
  {
    id: 'variation-07',
    name: 'Sideways Rain Day',
    loop: 'The child drags a leaf umbrella over damp little creatures while rain slants down and gusts sway the drops in beats, and each creature the drops miss relaxes; the slant, the gust rhythm, and the visitors change every day.',
    verb: 'shelter',
    ageBand: [3, 5],
    engine: 'variation',
    secondaryEngines: ['other-minds'],
    lens: 'other',
    toy: null,
    play5:
      'The child reads the slant of the falling streaks and holds the leaf on the windward side instead of straight overhead, and shifts it a beat ahead of each gust.',
  },
  {
    id: 'variation-08',
    name: 'Patchy Snowman',
    loop: "The child drags a snowball along a finger path across a meadow where snow lies in patches; it grows on fresh snow, sheds on bare grass, and leaves bare ground behind, until it fills the ghost outline of a snowman's body.",
    verb: 'trundle',
    ageBand: [5, 7],
    engine: 'variation',
    secondaryEngines: [],
    lens: 'other',
    toy: null,
    play5:
      "The child studies the day's snow patches first and plans one sweeping loop that gathers the thick snow once and cuts across bare grass, where on play 1 they wandered and ran out of snow.",
  },
  {
    id: 'variation-09',
    name: 'Scrapyard Toolbox',
    loop: "The child drags the three scrap tools dealt for the day (ramp plank, spring pad, fan, sponge, bumper) into a scene, then lets a ball roll from the chute toward a sleepy cat on a far shelf; the tools and the cat's spot change every day.",
    verb: 'rig',
    ageBand: [6, 9],
    engine: 'variation',
    secondaryEngines: ['combination', 'rule-play'],
    lens: 'other',
    toy: null,
    play5:
      'The child asks what each tool can do besides its obvious job, like using the fan to lift the ball over a wall or the sponge to stop it mid-ramp, and builds a working rig from a dealt set that has no obvious answer.',
  },
  {
    id: 'variation-10',
    name: 'Stones That Breathe',
    loop: "The child taps a stone to send a frog leaping toward a lily, and each river stone rises and sinks on its own slow period, so what is safe to land on shifts; each day's periods are new multiples of one hidden beat.",
    verb: 'leap',
    ageBand: [7, 10],
    engine: 'variation',
    secondaryEngines: ['mastery', 'mystery'],
    lens: 'other',
    toy: null,
    play5:
      "The child watches one full bob to find the day's shared beat, then waits at the bank for the instant the whole path is up and crosses in one run, where on play 1 they leapt stone by stone and got dunked.",
  },
  {
    id: 'variation-11',
    name: 'Bent Mirror Pond',
    loop: "The child drags a finger to sail a small boat through a row of buoys, but each day the pond bends the finger's motion (mirrored, turned sideways, doubled, or lagging behind) so the boat answers differently.",
    verb: 'pilot',
    ageBand: [8, 11],
    engine: 'variation',
    secondaryEngines: ['rule-play', 'mystery'],
    lens: 'other',
    toy: null,
    play5:
      "The child draws one small test wiggle to see how today's pond twists the finger, then plans the whole path through the twist and sails a clean line through the buoys, where on play 1 they fought the boat.",
  },
  {
    id: 'variation-12',
    name: 'Echoes in the Dark',
    loop: 'In a dark cave the child taps to send out a ring that flashes the hidden walls it meets, then drags a lost firefly through the gaps to the far light; the tunnels are new every visit.',
    verb: 'ping',
    ageBand: [10, 12],
    engine: 'variation',
    secondaryEngines: ['mystery'],
    lens: 'other',
    toy: null,
    play5:
      'The child reads the rings (a ring that stays round means open cave, one that snaps flat and flashes means a wall close by) and pings from the spot that lights the most tunnel, where on play 1 they tapped everywhere.',
  },
  {
    id: 'variation-13',
    name: 'Loop the Moons',
    loop: 'The child drags back and lets go to fling a small probe across a field where moons of different weights circle a sun and bend its path toward a marked dock; each visit arranges the moons differently.',
    verb: 'sling',
    ageBand: [10, 12],
    engine: 'variation',
    secondaryEngines: ['mastery', 'emergence'],
    lens: 'other',
    toy: null,
    play5:
      'The child times the release so a passing moon flings the probe onward, finding that the side it approaches decides where it leaves, a slingshot that a straight aim never shows.',
  },
  {
    id: 'variation-14',
    name: 'Dragon Bazaar',
    loop: 'The child drags trinkets to three stall-keepers who each swap one kind for another at their own fixed rate (shown as piles of pips), aiming to hand a shy dragon the gem it wants; every visit the rates are re-dealt.',
    verb: 'barter',
    ageBand: [10, 12],
    engine: 'variation',
    secondaryEngines: ['rule-play'],
    lens: 'other',
    toy: null,
    play5:
      'The child hunts for a round of swaps through the three stalls that ends with more of one thing than it began with and rides that round to afford the gem, where on play 1 they only tried straight trades.',
  },
]
