// Toon dusk: a peach-to-lilac sky over mint water and lilac pads. Warm
// light, lilac shadows, a gold rim from the setting sun behind the pond,
// and plum outlines (never black). Each frog wears its own warm hue so it
// reads against the cool pads and water.

export const PALETTE = {
  skyTop: '#a995d8',
  skyBands: ['#a995d8', '#c7a3dc', '#eaa9c8', '#fbbcae', '#ffcfa6', '#ffe2ae'],
  sun: '#fff4cf',
  sunGlow: '#ffe8b8',
  cloud: '#ffd9d2',
  cloudShade: '#f5b9bf',
  hillsFar: '#c4b2e6',
  hillsNear: '#a894d6',
  bank: '#6fae9c',
  bankLight: '#8cc7ad',
  bush: '#79b9a0',
  bushDark: '#5f9c8d',
  waterNear: '#8fd8c6',
  waterFar: '#b9e3d2',
  waterGlint: '#fff1d6',
  waterDusk: '#f4c7c0',
  splash: '#eefffa',
  pad: '#c7a2e4',
  padLight: '#dcc2f2',
  padSide: '#9e7fcb',
  padVein: '#ecdcfa',
  reed: '#88bf98',
  reedDark: '#6aa487',
  cattail: '#c98a74',
  outline: '#574373',
  shadow: '#4f3f78',
  fog: '#e7c3d2',
  fireflyGlow: '#ffe48c',
  fireflyCore: '#fff27a',
  fireflyBody: '#5b4668',
  fireflyWing: '#ffffff',
  glow: '#ffe07a',
  eyeWhite: '#ffffff',
  pupil: '#35294a',
  mouth: '#6b3a55',
  mouthInside: '#8e3f5c',
  cheek: '#ff97ad',
  keyLight: '#ffe6cc',
  hemiSky: '#ffe0cf',
  hemiGround: '#a58fd6',
  rim: '#ffcf8a',
  hand: '#ffffff',
  handLine: '#6a5078',
} as const
